version: "3"
services:
  hub:
    image: selenium/hub:3.141.59-20200525
  chrome:
    image: selenium/node-chrome:3.141.59-20200525
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.141.59-20200525
    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  seleniumtest:
    image: varadharajan17/selenium-test
    depends_on:
      - chrome
    environment:
      - HUB_HOST=hub
      - MODULE=TestNG.xml
      - BROWSER=chrome
    volumes:
      - ./output/selenium-test:/usr/share/seleniumtest/test-output